name: Update git-cb Formula

on:
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Update git-cb formula
        run: ./scripts/update-git-cb
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Formula/git-cb.rb
          git diff --staged --quiet || (git commit -m "Update git-cb to latest version" && git push)
